// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.27.3
// source: search.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SemanticSearchService_IndexProducts_FullMethodName = "/search.SemanticSearchService/IndexProducts"
	SemanticSearchService_Search_FullMethodName        = "/search.SemanticSearchService/Search"
)

// SemanticSearchServiceClient is the client API for SemanticSearchService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The Semantic Search Service
type SemanticSearchServiceClient interface {
	IndexProducts(ctx context.Context, in *IndexRequest, opts ...grpc.CallOption) (*IndexResponse, error)
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
}

type semanticSearchServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSemanticSearchServiceClient(cc grpc.ClientConnInterface) SemanticSearchServiceClient {
	return &semanticSearchServiceClient{cc}
}

func (c *semanticSearchServiceClient) IndexProducts(ctx context.Context, in *IndexRequest, opts ...grpc.CallOption) (*IndexResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IndexResponse)
	err := c.cc.Invoke(ctx, SemanticSearchService_IndexProducts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *semanticSearchServiceClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, SemanticSearchService_Search_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SemanticSearchServiceServer is the server API for SemanticSearchService service.
// All implementations must embed UnimplementedSemanticSearchServiceServer
// for forward compatibility.
//
// The Semantic Search Service
type SemanticSearchServiceServer interface {
	IndexProducts(context.Context, *IndexRequest) (*IndexResponse, error)
	Search(context.Context, *SearchRequest) (*SearchResponse, error)
	mustEmbedUnimplementedSemanticSearchServiceServer()
}

// UnimplementedSemanticSearchServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSemanticSearchServiceServer struct{}

func (UnimplementedSemanticSearchServiceServer) IndexProducts(context.Context, *IndexRequest) (*IndexResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IndexProducts not implemented")
}
func (UnimplementedSemanticSearchServiceServer) Search(context.Context, *SearchRequest) (*SearchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedSemanticSearchServiceServer) mustEmbedUnimplementedSemanticSearchServiceServer() {}
func (UnimplementedSemanticSearchServiceServer) testEmbeddedByValue()                               {}

// UnsafeSemanticSearchServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SemanticSearchServiceServer will
// result in compilation errors.
type UnsafeSemanticSearchServiceServer interface {
	mustEmbedUnimplementedSemanticSearchServiceServer()
}

func RegisterSemanticSearchServiceServer(s grpc.ServiceRegistrar, srv SemanticSearchServiceServer) {
	// If the following call panics, it indicates UnimplementedSemanticSearchServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SemanticSearchService_ServiceDesc, srv)
}

func _SemanticSearchService_IndexProducts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IndexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SemanticSearchServiceServer).IndexProducts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SemanticSearchService_IndexProducts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SemanticSearchServiceServer).IndexProducts(ctx, req.(*IndexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SemanticSearchService_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SemanticSearchServiceServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SemanticSearchService_Search_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SemanticSearchServiceServer).Search(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SemanticSearchService_ServiceDesc is the grpc.ServiceDesc for SemanticSearchService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SemanticSearchService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "search.SemanticSearchService",
	HandlerType: (*SemanticSearchServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IndexProducts",
			Handler:    _SemanticSearchService_IndexProducts_Handler,
		},
		{
			MethodName: "Search",
			Handler:    _SemanticSearchService_Search_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "search.proto",
}
