'use client';

import React, { useState, useEffect } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { ChevronLeft } from 'lucide-react';

interface ProductOption {
  id?: number;
  name: string;
  values: string;
}

interface ProductVariant {
  id: number;
  title: string;
  option1: string;
  option2: string;
  option3: string;
  option4: string;
  option5: string;
  sku: string;
  price: number;
  compare_at_price?: number;
  stock_quantity: number;
  image_url?: string;
}

interface Product {
  id: number;
  title: string;
  description: string;
  price: number;
  compare_at_price?: number;
  image_url: string;
  category_id: number | null;
  options?: ProductOption[];
  variants?: ProductVariant[];
}

import { useCurrency } from './CurrencyProvider';

// Helper component to safely execute scripts generated by AI
function useDynamicScripts(htmlContent: string) {
  useEffect(() => {
    if (!htmlContent) return;
    
    // Find the container where the HTML is injected
    const container = document.getElementById('product-description-container');
    if (!container) return;

    // Find all script tags that were injected
    const scripts = container.getElementsByTagName('script');
    
    // For each script tag, we have to create a NEW script tag and append it 
    // to the DOM for the browser to actually execute the JS code.
    Array.from(scripts).forEach((oldScript) => {
      const newScript = document.createElement('script');
      Array.from(oldScript.attributes).forEach((attr) => {
        newScript.setAttribute(attr.name, attr.value);
      });
      newScript.appendChild(document.createTextNode(oldScript.innerHTML));
      oldScript.parentNode?.replaceChild(newScript, oldScript);
    });
  }, [htmlContent]);
}

export default function ProductView({ product, currency }: { product: Product, currency?: string }) {
  const { formatPrice } = useCurrency();
  const router = useRouter();

  useDynamicScripts(product.description || '');

  const [selectedVariant, setSelectedVariant] = useState<ProductVariant | null>(null);
  const [selectedOptions, setSelectedOptions] = useState<string[]>([]);
  
  useEffect(() => {
    // We intentionally leave selectedVariant null initially if there are options,
    // so that the price range displays until the user makes a full selection.
    if (!product.options || product.options.length === 0) {
      if (product.variants && product.variants.length > 0) {
        // eslint-disable-next-line react-hooks/set-state-in-effect
        setSelectedVariant(product.variants[0]);
      }
    }
  }, [product]);

  const handleOptionSelect = (optionIndex: number, value: string) => {
    const newOptions = [...selectedOptions];
    newOptions[optionIndex] = value;
    setSelectedOptions(newOptions);

    const matched = product.variants?.find(v => 
      v.option1 === (newOptions[0] || '') &&
      v.option2 === (newOptions[1] || '') &&
      v.option3 === (newOptions[2] || '') &&
      v.option4 === (newOptions[3] || '') &&
      v.option5 === (newOptions[4] || '')
    );
    if (matched) setSelectedVariant(matched);
  };

  const currentImage = selectedVariant?.image_url || product.image_url;

  const getPriceDisplay = () => {
    if (selectedVariant) {
      return (
        <div className="flex items-center space-x-3 mb-8">
          <p className="text-3xl font-semibold text-zinc-900">{formatPrice(selectedVariant.price)}</p>
          {selectedVariant.compare_at_price && selectedVariant.compare_at_price > selectedVariant.price ? (
            <p className="text-xl font-medium text-zinc-400 line-through">{formatPrice(selectedVariant.compare_at_price)}</p>
          ) : null}
        </div>
      );
    }
    
    if (product.variants && product.variants.length > 0) {
      const prices = product.variants.map(v => v.price);
      const min = Math.min(...prices);
      const max = Math.max(...prices);
      return (
        <div className="flex items-center space-x-3 mb-8">
          <p className="text-3xl font-semibold text-zinc-900">
            {min === max ? formatPrice(min) : `${formatPrice(min)} - ${formatPrice(max)}`}
          </p>
        </div>
      );
    }

    return (
      <div className="flex items-center space-x-3 mb-8">
        <p className="text-3xl font-semibold text-zinc-900">{formatPrice(product.price)}</p>
        {product.compare_at_price && product.compare_at_price > product.price ? (
          <p className="text-xl font-medium text-zinc-400 line-through">{formatPrice(product.compare_at_price)}</p>
        ) : null}
      </div>
    );
  };

  return (
    <div className="w-full min-h-screen bg-zinc-50 pt-24 pb-20">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        
        {/* Back Button */}
        <Link href="/" className="inline-flex items-center text-sm font-medium text-zinc-500 hover:text-zinc-900 mb-8 transition-colors">
          <ChevronLeft className="w-4 h-4 mr-1" />
          Back to Store
        </Link>
        
        <div className="bg-white rounded-3xl overflow-hidden shadow-sm border border-zinc-100 flex flex-col md:flex-row">
          
          {/* Left Column: Image */}
          <div className="w-full md:w-1/2 bg-zinc-100 aspect-square md:aspect-auto flex items-center justify-center relative">
            {currentImage ? (
              <img src={currentImage} alt={selectedVariant ? selectedVariant.title : product.title} className="w-full h-full object-cover" />
            ) : (
              <div className="text-zinc-400 font-medium">No Image Available</div>
            )}
          </div>

          {/* Right Column: Details */}
          <div className="w-full md:w-1/2 p-8 md:p-14 lg:p-16 flex flex-col bg-white">
            <h1 className="text-4xl font-extrabold text-zinc-900 mb-4 tracking-tight">{product.title}</h1>
            
            {getPriceDisplay()}
            
            <div 
              id="product-description-container"
              className="prose prose-zinc prose-lg text-zinc-500 mb-10 max-w-none leading-relaxed [&>table]:w-full [&>table]:border-collapse [&>table]:my-6 [&_th]:bg-zinc-50 [&_th]:p-3 [&_th]:border [&_th]:border-zinc-200 [&_th]:text-left [&_th]:font-semibold [&_th]:text-zinc-900 [&_td]:p-3 [&_td]:border [&_td]:border-zinc-200 [&_td]:text-zinc-600 [&_ul]:list-disc [&_ul]:pl-5 [&_ul]:my-4 [&_ul_li]:pl-2 [&_ul_li]:marker:text-zinc-400"
              dangerouslySetInnerHTML={{ __html: product.description }}
            />

            {/* Options */}
            {product.options && product.options.length > 0 && (
              <div className="mb-10 space-y-6">
                {product.options.map((opt, optIndex) => {
                  const values = opt.values.split(',').map(v => v.trim()).filter(v => v);
                  return (
                    <div key={opt.id || optIndex}>
                      <h3 className="text-sm font-bold text-zinc-900 mb-3 uppercase tracking-wider">{opt.name}</h3>
                      <div className="flex flex-wrap gap-3">
                        {values.map(val => {
                          const isSelected = selectedOptions[optIndex] === val;
                          return (
                            <button
                              key={val}
                              onClick={() => handleOptionSelect(optIndex, val)}
                              className={`px-5 py-3 rounded-xl text-sm font-semibold border-2 transition-all ${
                                isSelected 
                                  ? 'border-zinc-900 bg-zinc-900 text-white shadow-md shadow-zinc-900/20 scale-[1.02]' 
                                  : 'border-zinc-200 bg-white text-zinc-700 hover:border-zinc-300 hover:bg-zinc-50'
                              }`}
                            >
                              {val}
                            </button>
                          );
                        })}
                      </div>
                    </div>
                  );
                })}
              </div>
            )}

            {/* Add to Cart Area */}
            <div className="mt-auto pt-6 border-t border-zinc-100">
              <button 
                disabled={product.options && product.options.length > 0 && !selectedVariant}
                onClick={() => {
                  const cartItem = {
                    variant_id: selectedVariant ? selectedVariant.id : (product.variants?.[0]?.id || 0),
                    quantity: 1,
                    product: {
                      title: product.title,
                      price: selectedVariant ? selectedVariant.price : product.price,
                      image_url: selectedVariant?.image_url || product.image_url
                    }
                  };
                  const currentCart = JSON.parse(localStorage.getItem('cart') || '[]');
                  currentCart.push(cartItem);
                  localStorage.setItem('cart', JSON.stringify(currentCart));
                  window.dispatchEvent(new Event('cart_updated'));
                  // Provide user feedback (can redirect to cart or stay)
                  alert('Added to cart!');
                }}
                className="w-full bg-zinc-900 text-white py-5 rounded-2xl text-lg font-bold hover:bg-zinc-800 transition-colors shadow-xl shadow-zinc-900/20 active:scale-[0.98] disabled:opacity-50 disabled:active:scale-100 disabled:shadow-none"
              >
                {product.options && product.options.length > 0 && !selectedVariant 
                  ? 'Select Options' 
                  : `Add to Cart - ${formatPrice(selectedVariant ? selectedVariant.price : product.price)}`}
              </button>
              
              <div className="mt-6 flex items-center justify-center text-sm text-zinc-500 space-x-6">
                <span className="flex items-center">
                  <svg className="w-5 h-5 mr-2 text-zinc-400" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M5 13l4 4L19 7"></path></svg>
                  In stock
                </span>
                <span className="flex items-center">
                  <svg className="w-5 h-5 mr-2 text-zinc-400" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 15v2m-6 4h12a2 2 0 002-2v-6a2 2 0 00-2-2H6a2 2 0 00-2 2v6a2 2 0 002 2zm10-10V7a4 4 0 00-8 0v4h8V7a4 4 0 00-8 0v4h8z"></path></svg>
                  Secure checkout
                </span>
              </div>
            </div>

          </div>
        </div>
      </div>
    </div>
  );
}
