// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Order struct {
	ID            string       `json:"id"`
	CustomerEmail *string      `json:"customer_email,omitempty"`
	TotalAmount   float64      `json:"total_amount"`
	Status        string       `json:"status"`
	PaymentMethod *string      `json:"payment_method,omitempty"`
	CreatedAt     string       `json:"created_at"`
	Items         []*OrderItem `json:"items,omitempty"`
}

type OrderItem struct {
	ID       string  `json:"id"`
	OrderID  int     `json:"order_id"`
	Title    string  `json:"title"`
	Quantity int     `json:"quantity"`
	Price    float64 `json:"price"`
}

type Product struct {
	ID                string            `json:"id"`
	Title             string            `json:"title"`
	Description       *string           `json:"description,omitempty"`
	Sku               *string           `json:"sku,omitempty"`
	Price             float64           `json:"price"`
	CompareAtPrice    *float64          `json:"compare_at_price,omitempty"`
	InventoryQuantity int               `json:"inventory_quantity"`
	Status            string            `json:"status"`
	IsActive          bool              `json:"is_active"`
	Variants          []*ProductVariant `json:"variants,omitempty"`
}

type ProductVariant struct {
	ID                string  `json:"id"`
	ProductID         int     `json:"product_id"`
	Title             string  `json:"title"`
	Sku               *string `json:"sku,omitempty"`
	Price             float64 `json:"price"`
	InventoryQuantity int     `json:"inventory_quantity"`
}

type Query struct {
}
