package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
	"eaas-backend/graph/model"
	"fmt"
)

// GetProducts is the resolver for the getProducts field.
func (r *queryResolver) GetProducts(ctx context.Context, shopID string) ([]*model.Product, error) {
	if r.GetProductsFunc != nil {
		return r.GetProductsFunc(ctx, shopID)
	}
	return nil, fmt.Errorf("not implemented")
}

// GetOrders is the resolver for the getOrders field.
func (r *queryResolver) GetOrders(ctx context.Context, shopID string) ([]*model.Order, error) {
	if r.GetOrdersFunc != nil {
		return r.GetOrdersFunc(ctx, shopID)
	}
	return nil, fmt.Errorf("not implemented")
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//  - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//    it when you're done.
//  - You have helper methods in this file. Move them out to keep these resolver files clean.
/*
	func (r *orderResolver) ID(ctx context.Context, obj *main.Order) (string, error) {
	panic(fmt.Errorf("not implemented: ID - id"))
}
func (r *orderResolver) CreatedAt(ctx context.Context, obj *main.Order) (string, error) {
	panic(fmt.Errorf("not implemented: CreatedAt - created_at"))
}
func (r *orderItemResolver) ID(ctx context.Context, obj *main.OrderItem) (string, error) {
	panic(fmt.Errorf("not implemented: ID - id"))
}
func (r *orderItemResolver) OrderID(ctx context.Context, obj *main.OrderItem) (int, error) {
	panic(fmt.Errorf("not implemented: OrderID - order_id"))
}
func (r *productResolver) ID(ctx context.Context, obj *main.Product) (string, error) {
	panic(fmt.Errorf("not implemented: ID - id"))
}
func (r *productResolver) Sku(ctx context.Context, obj *main.Product) (*string, error) {
	panic(fmt.Errorf("not implemented: Sku - sku"))
}
func (r *productResolver) InventoryQuantity(ctx context.Context, obj *main.Product) (int, error) {
	panic(fmt.Errorf("not implemented: InventoryQuantity - inventory_quantity"))
}
func (r *productResolver) Status(ctx context.Context, obj *main.Product) (string, error) {
	panic(fmt.Errorf("not implemented: Status - status"))
}
func (r *productResolver) IsActive(ctx context.Context, obj *main.Product) (bool, error) {
	panic(fmt.Errorf("not implemented: IsActive - is_active"))
}
func (r *productVariantResolver) ID(ctx context.Context, obj *main.ProductVariant) (string, error) {
	panic(fmt.Errorf("not implemented: ID - id"))
}
func (r *productVariantResolver) ProductID(ctx context.Context, obj *main.ProductVariant) (int, error) {
	panic(fmt.Errorf("not implemented: ProductID - product_id"))
}
func (r *productVariantResolver) InventoryQuantity(ctx context.Context, obj *main.ProductVariant) (int, error) {
	panic(fmt.Errorf("not implemented: InventoryQuantity - inventory_quantity"))
}
func (r *Resolver) Order() OrderResolver { return &orderResolver{r} }
func (r *Resolver) OrderItem() OrderItemResolver { return &orderItemResolver{r} }
func (r *Resolver) Product() ProductResolver { return &productResolver{r} }
func (r *Resolver) ProductVariant() ProductVariantResolver { return &productVariantResolver{r} }
type (
	orderResolver          struct{ *Resolver }
	orderItemResolver      struct{ *Resolver }
	productResolver        struct{ *Resolver }
	productVariantResolver struct{ *Resolver }
	queryResolver          struct{ *Resolver }
)
*/
